# Generated by Django 4.2.7 on 2024-03-15 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieuhabitationactuelle', models.CharField(max_length=100, null=True)),
                ('situationmatrimoniale', models.CharField(max_length=50, null=True)),
                ('fonction', models.CharField(max_length=50, null=True)),
                ('datecreation', models.DateField(default=datetime.date.today)),
                ('besoin', models.CharField(max_length=200, null=True)),
                ('contact1', models.CharField(max_length=50)),
                ('contact2', models.CharField(max_length=50, null=True)),
                ('budget', models.IntegerField(default=0)),
                ('adressemail', models.EmailField(max_length=50, null=True)),
                ('commentaire', models.CharField(max_length=200, null=True)),
                ('statut', models.CharField(max_length=50, null=True)),
                ('datenaisloca', models.DateField(null=True)),
                ('lieunaissloca', models.CharField(max_length=50, null=True)),
                ('naturepieceloca', models.CharField(max_length=50, null=True)),
                ('dateeditionpiece', models.DateField(null=True)),
                ('datefinpiece', models.DateField(null=True)),
                ('numpiece', models.CharField(max_length=50, null=True)),
                ('employeurloca', models.CharField(max_length=50, null=True)),
                ('lieueditionpiece', models.CharField(max_length=50, null=True)),
                ('adressepostalloca', models.CharField(max_length=50, null=True)),
                ('nombreenfant', models.IntegerField(default=0, null=True)),
                ('personnecasurgent', models.CharField(max_length=50, null=True)),
                ('dateeffet', models.DateField(null=True)),
                ('photoloca', models.BinaryField(null=True)),
                ('nationnaliteloca', models.CharField(max_length=50, null=True)),
                ('contacturgence', models.CharField(max_length=50, null=True)),
                ('capital', models.BigIntegerField(default=0, null=True)),
                ('representant', models.CharField(max_length=50, null=True)),
                ('contact1representant', models.CharField(max_length=50, null=True)),
                ('mailrepesentant', models.EmailField(max_length=254, null=True)),
                ('ncc', models.CharField(max_length=50, null=True)),
                ('rc', models.CharField(max_length=50, null=True)),
                ('siegesocial', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='typeappartement',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='Caution',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='Cautioncie',
        ),
        migrations.RemoveField(
            model_name='contratbail',
            name='locataire',
        ),
        migrations.RemoveField(
            model_name='contratbail',
            name='typeappartement',
        ),
        migrations.AddField(
            model_name='contratbail',
            name='datecration',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='genre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bien',
            name='assurance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='circonscription',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bien',
            name='commentaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='commune',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='datecreation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bien',
            name='delaispaiement',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='docs',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='enregistrementbail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fraisagence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fraisrenouvellement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='legislationbau',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='localisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='quartier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='revenumensuel',
            field=models.BigIntegerField(default=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='superficie',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='usage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='Statut',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='caution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='cautioncie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='descriptions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='fraisagence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='loyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='loyeravance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='nbrepieces',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='superficie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='activite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='adressepostalloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='adresspostalrepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='appartement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='bailleur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='capital',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='capitalclient',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='casurgence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='cnirepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='codefacturefrais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='composantsite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='contacturgence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datedebut',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='dateeditionpiece',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='dateeditionpiecerepresentant',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='dateexpirationpiecerepresentant',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datefin',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datenaisloca',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datenaissancerepresentant',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datenaissloca',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='datesaisie',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='delaispaiement',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='depotgarantie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='descriptionsappartement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='dureecontrat',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='dureerevision',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='emailrepresentant',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='emailstruc',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='employeurloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='fonctionloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='fraisagence',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='fraisrecouvement',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='ilot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='lieueditionpiece',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='lieueditionpiecerepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='lieunaissancerepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='lieunaissloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='localisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='lot',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='loyer',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='loyeravance',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nationnaliteloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nationnaliterepresent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='naturepieceloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nbrepieces',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nccstruc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nomloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='nomrepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='numpieceloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='penalite',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='professionrepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='rcc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='regimesocial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='representant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='saisiepar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='siegesocialclient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='siegestruc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='situationmatrimoniale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='tacherepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='telloca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='telrepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='telstruc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='totacontrat',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='typebail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contratbail',
            name='whatsapprepresentant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ResteAPayer',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='appartement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='contactproprio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='datecontrat',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateedition',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='datefacture',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='facture',
            name='delaispaiement',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='doit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='editepar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='emaiproprietaire',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='localisation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='loyer',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montantpenalite',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='montantregle',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='nature',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='netApayer',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numappartement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numquitance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='soustotal',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='totalttc',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='totaltva',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='adressemail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='boitepostale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='contact1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='contact1representant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='contact2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='contacturgence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='fonctions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='lieuhabitation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='lieunaissance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='nationnalite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='naturepiece',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='numcompte',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='numpiece',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='personneurgence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='representant',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='situationmatrimoniale',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='locataire',
        ),
        migrations.DeleteModel(
            name='prospect',
        ),
        migrations.DeleteModel(
            name='typeappartement',
        ),
        migrations.AddField(
            model_name='bien',
            name='caution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='cautioncie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contratbail',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigim.client'),
            preserve_default=False,
        ),
    ]
