# Generated by Django 4.2.7 on 2024-03-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0002_client_remove_prospect_typeappartement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='typebien',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='typebien',
        ),
    ]
