# Generated by Django 4.2.7 on 2024-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0004_alter_bien_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='compbien',
            name='nature',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
