# Generated by Django 4.2.7 on 2024-03-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0005_compbien_nature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bien',
            options={'verbose_name': 'Bien', 'verbose_name_plural': 'Biens'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='compbien',
            options={'verbose_name': 'Composant', 'verbose_name_plural': 'Composants'},
        ),
        migrations.AlterModelOptions(
            name='contratbail',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='proprietaire',
            options={'verbose_name': 'Proprietaire', 'verbose_name_plural': 'Proprietaires'},
        ),
    ]
