# Generated by Django 4.2.7 on 2024-03-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0006_alter_bien_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typepiece',
            name='libelle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
