# Generated by Django 4.2.7 on 2024-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0007_alter_typepiece_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='loyeravance',
            field=models.IntegerField(null=True),
        ),
    ]
