# Generated by Django 4.2.7 on 2024-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0008_bien_loyeravance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dateeffet',
        ),
        migrations.AlterField(
            model_name='client',
            name='photoloca',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
