# Generated by Django 4.2.7 on 2024-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0009_remove_client_dateeffet_alter_client_photoloca'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='genre',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
