# Generated by Django 4.2.7 on 2024-03-26 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0011_client_localite'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typebail', models.CharField(max_length=50)),
                ('datecration', models.DateField(default=datetime.date.today)),
                ('datedebut', models.DateField(default='', null=True)),
                ('datefin', models.DateField(default='', null=True)),
                ('dureecontrat', models.IntegerField(default=0, null=True)),
                ('datedernierreglement', models.DateField(default=0, null=True)),
                ('dateprochainreglement', models.DateField(default=0, null=True)),
                ('delaispaiement', models.IntegerField(default='', null=True)),
                ('loyer', models.BigIntegerField(default=0, null=True)),
                ('penalite', models.BigIntegerField(default=0, null=True)),
                ('depotgarantie', models.IntegerField(default=0, null=True)),
                ('fraisagence', models.BigIntegerField(default=0, null=True)),
                ('cautioncie', models.BigIntegerField(default=0, null=True)),
                ('statut', models.CharField(default='', max_length=50)),
                ('saisiepar', models.CharField(max_length=50, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.client')),
                ('compbien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.compbien')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.proprietaire')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
            },
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='ResteAPayer',
            new_name='resteapayer',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='appartement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='bien',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='contactproprio',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='contratbail',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='datecontrat',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='emaiproprietaire',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='numappartement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='typeappartement',
        ),
        migrations.DeleteModel(
            name='contratbail',
        ),
        migrations.AddField(
            model_name='facture',
            name='contrat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigim.contrat'),
            preserve_default=False,
        ),
    ]
