# Generated by Django 4.2.7 on 2024-03-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0012_contrat_rename_resteapayer_facture_resteapayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='netApayer',
            new_name='netapayer',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='proprietaire',
        ),
        migrations.AddField(
            model_name='contrat',
            name='caution',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='loyeravance',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='nbremoiscaution',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='newuser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigim.newuser'),
            preserve_default=False,
        ),
    ]
