# Generated by Django 4.2.7 on 2024-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0013_rename_netapayer_facture_netapayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='commentaire',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
