# Generated by Django 4.2.7 on 2024-03-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0014_contrat_commentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typepiece',
            old_name='libelle',
            new_name='libel',
        ),
    ]
