# Generated by Django 4.2.7 on 2024-04-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0015_rename_libelle_typepiece_libel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bien',
            options={},
        ),
    ]
