# Generated by Django 4.2.7 on 2024-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0016_alter_bien_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='statut',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
