# Generated by Django 4.2.7 on 2024-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0017_proprietaire_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compbien',
            options={},
        ),
        migrations.AddField(
            model_name='compbien',
            name='depotgarantie',
            field=models.IntegerField(null=True),
        ),
    ]
