# Generated by Django 4.2.7 on 2024-04-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0019_remove_contrat_nbremoiscaution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='docs',
            field=models.FileField(null=True, upload_to='documents'),
        ),
    ]
