# Generated by Django 4.2.7 on 2024-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0020_alter_bien_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('photo', models.ImageField(upload_to='imagetest/')),
                ('doc', models.FileField(upload_to='filetest/')),
            ],
        ),
    ]
