# Generated by Django 4.2.7 on 2024-04-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0021_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='tests',
        ),
    ]
