# Generated by Django 4.2.7 on 2024-04-15 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0023_alter_tests_doc_alter_tests_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compbien',
            name='datecreation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
