# Generated by Django 4.2.7 on 2024-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0024_compbien_datecreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='numtitreproprite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='titreproprite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='assurance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='cautioncie',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='circonscription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='docs',
            field=models.FileField(default='', null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='enregistrementbail',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fraisagence',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='fraisrenouvellement',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='iLot',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='lot',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='bien',
            name='loyeravance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
