# Generated by Django 4.2.7 on 2024-04-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0025_bien_numtitreproprite_bien_titreproprite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='status',
        ),
    ]
