# Generated by Django 4.2.7 on 2024-04-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0027_remove_client_employeurloca_remove_client_photoloca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='saisiepar',
        ),
    ]
