# Generated by Django 4.2.7 on 2024-04-25 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0028_remove_contrat_saisiepar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='datecration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
