# Generated by Django 4.2.7 on 2024-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0029_alter_contrat_datecration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='dureecontrat',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
