# Generated by Django 4.2.7 on 2024-04-25 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0030_alter_contrat_dureecontrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bien',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='compbien',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='dateedition',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
