# Generated by Django 4.2.7 on 2024-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0031_proprietaire_datecreation_alter_bien_datecreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='dateedition',
            field=models.DateField(default='', null=True),
        ),
    ]
