# Generated by Django 4.2.7 on 2024-04-25 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0032_alter_facture_dateedition'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='typefacture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeproforma', models.CharField(max_length=50, null=True)),
                ('dateproforma', models.DateField(default=datetime.date.today)),
                ('doit', models.CharField(max_length=50, null=True)),
                ('soustotal', models.BigIntegerField(default=0, null=True)),
                ('totaltva', models.BigIntegerField(default=0, null=True)),
                ('totalttc', models.BigIntegerField(default=0, null=True)),
                ('loyer', models.BigIntegerField(default=0, null=True)),
                ('remise', models.BigIntegerField(default=0, null=True)),
                ('netapayer', models.BigIntegerField(default=0, null=True)),
                ('delaispaiement', models.IntegerField(default=0, null=True)),
                ('editepar', models.CharField(max_length=50, null=True)),
                ('dateedition', models.DateField(default='', null=True)),
                ('numquitance', models.CharField(max_length=50, null=True)),
                ('nature', models.CharField(max_length=50, null=True)),
                ('montantregle', models.BigIntegerField(default=0, null=True)),
                ('resteapayer', models.BigIntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.bien')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.proprietaire')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
            },
        ),
        migrations.CreateModel(
            name='mandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typemandat', models.CharField(max_length=50)),
                ('datecration', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('datedebut', models.DateField(default='', null=True)),
                ('datefin', models.DateField(default='', null=True)),
                ('dureecontrat', models.CharField(default='', max_length=50, null=True)),
                ('delaispaiement', models.IntegerField(default='', null=True)),
                ('revenumensuel', models.BigIntegerField(default=0, null=True)),
                ('fraisdossier', models.BigIntegerField(default=0, null=True)),
                ('statut', models.CharField(default='', max_length=50)),
                ('commentaire', models.CharField(default='', max_length=500, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.bien')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.facture')),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.newuser')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.proprietaire')),
            ],
            options={
                'verbose_name': 'mandat',
                'verbose_name_plural': 'mandats',
            },
        ),
        migrations.CreateModel(
            name='detailsproforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('soustotal', models.BigIntegerField(default=0, null=True)),
                ('totaltva', models.BigIntegerField(default=0, null=True)),
                ('totalttc', models.BigIntegerField(default=0, null=True)),
                ('remise', models.BigIntegerField(default=0, null=True)),
                ('netapayer', models.BigIntegerField(default=0, null=True)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.proforma')),
            ],
            options={
                'verbose_name': 'detailproforma',
                'verbose_name_plural': 'detailproformas',
            },
        ),
        migrations.CreateModel(
            name='detailsfacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, null=True)),
                ('soustotal', models.BigIntegerField(default=0, null=True)),
                ('totaltva', models.BigIntegerField(default=0, null=True)),
                ('totalttc', models.BigIntegerField(default=0, null=True)),
                ('remise', models.BigIntegerField(default=0, null=True)),
                ('netapayer', models.BigIntegerField(default=0, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.facture')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigim.proforma')),
            ],
            options={
                'verbose_name': 'detailfacture',
                'verbose_name_plural': 'detailfactures',
            },
        ),
    ]
