# Generated by Django 4.2.7 on 2024-04-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0034_detailsproforma_typeproforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='compbien',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigim.compbien'),
            preserve_default=False,
        ),
    ]
