# Generated by Django 4.2.7 on 2024-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0035_proforma_compbien'),
    ]

    operations = [
        migrations.CreateModel(
            name='lignedevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('montant', models.BigIntegerField(default=0)),
            ],
        ),
    ]
