# Generated by Django 4.2.7 on 2024-04-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0036_lignedevis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lignedevis',
            new_name='prestattions',
        ),
    ]
