# Generated by Django 4.2.7 on 2024-05-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0038_prestations_delete_prestattions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestations',
            name='description',
            field=models.CharField(default=0, max_length=105),
        ),
    ]
