# Generated by Django 4.2.7 on 2024-05-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0039_alter_prestations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='usage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
