# Generated by Django 4.2.7 on 2024-05-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0040_proforma_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('admail', models.EmailField(max_length=50)),
                ('fonction', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10)),
                ('photoid', models.ImageField(default='', null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='compbien',
        ),
        migrations.AddField(
            model_name='proforma',
            name='personnel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sigim.personnel'),
            preserve_default=False,
        ),
    ]
