# Generated by Django 4.2.7 on 2024-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0041_personnel_remove_proforma_compbien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='delaispaiement',
            field=models.DateField(default='', null=True),
        ),
    ]
