# Generated by Django 4.2.7 on 2024-05-06 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0042_alter_proforma_delaispaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='dateedition',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
