# Generated by Django 4.2.7 on 2024-05-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0043_alter_proforma_dateedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='dateedition',
            field=models.DateField(default='', null=True),
        ),
    ]
