# Generated by Django 4.2.7 on 2024-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0046_alter_detailsproforma_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='observation',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
