# Generated by Django 4.2.7 on 2024-05-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0048_remove_facture_contrat_facture_contrat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='contrat_id',
        ),
    ]
