# Generated by Django 4.2.7 on 2024-05-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0050_alter_facture_delaispaiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsproforma',
            old_name='description',
            new_name='prestations',
        ),
    ]
