# Generated by Django 4.2.7 on 2024-05-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0051_rename_description_detailsproforma_prestations'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sigim.proprietaire'),
            preserve_default=False,
        ),
    ]
