# Generated by Django 4.2.7 on 2024-05-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0053_regfactm'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='proforma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sigim.proforma'),
            preserve_default=False,
        ),
    ]
