# Generated by Django 4.2.7 on 2024-05-22 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sigim', '0054_facture_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='bien',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sigim.bien'),
            preserve_default=False,
        ),
    ]
